# Generated by Django 3.2.8 on 2022-01-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_days', models.CharField(choices=[('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_in_course', models.CharField(choices=[('Arit', 'Aritmética'), ('Alg', 'Álgebra'), ('Geom', 'Geometria'), ('Port', 'Português'), ('Hist', 'História'), ('Geo', 'Geografia'), ('Fis', 'Física'), ('Qui', 'Química'), ('Red', 'Redação'), ('Lit', 'Literatura')], default='Arit', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text='Curso dos seus sonhos!', max_length=20)),
                ('days', models.ManyToManyField(to='spreadsheet.Days')),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='subjects',
            field=models.ManyToManyField(to='spreadsheet.Subjects'),
        ),
    ]
