# Generated by Django 3.2.8 on 2022-01-16 01:00

from django.db import migrations, models
import spreadsheet.models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjects_in_course',
            field=models.CharField(default=[spreadsheet.models.Subjects.type_subjects], max_length=4),
        ),
    ]
