# Generated by Django 3.2.8 on 2022-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_auto_20220115_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type_subjects',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjects_in_course',
            field=models.CharField(choices=[('Arit', 'Aritmética'), ('Alg', 'Álgebra'), ('Geom', 'Geometria'), ('Port', 'Português'), ('Hist', 'História'), ('Geo', 'Geografia'), ('Fis', 'Física'), ('Qui', 'Química'), ('Red', 'Redação'), ('Lit', 'Literatura'), ('Socio', 'Sociologia'), ('Filo', 'Filosofia')], default='Mat1', max_length=7),
        ),
    ]
